"""initial

Revision ID: 3364fc22337b
Revises: babfa5ab2c72
Create Date: 2023-08-28 01:12:46.105593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3364fc22337b'
down_revision = 'babfa5ab2c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###